### ISSUE TITLE
Couldn't put a manual Database Password on process epadmin create

### ISSUE THREAD

**Issue by haniefhan** [eprints/eprints3.4#174]
Hi,
So I am trying to create a new Eprints archive with predefined db parameter by company DB Administrator, like :
- host : 10.10.1.18
- dbname : db_eprints
- dbuser : user_eprints
- dbpass : BSNeprints2021

I start the creatinng process with command `/usr/share/eprints/bin/epadmin create pub`.

Everything is ok, until I am trying put the `Database Password [iGZ6ZyCDeDhI6ETD]?`.
So, I put the database password `BSNeprints2021`, but an error message raised:
```
a valid variable name (lowercase letters, numbers and underscores only)
```
Why this is happening?
Hmmm.... the default has an uppercase letters too (`iGZ6ZyCDeDhI6ETD`), but why we can't use it for our own password?

Please fix it.

**Comment by haniefhan** [comment]
umm....
BTW, I found where the problem is and the solution.
I want to contribute in this project, can anyone tell me how to do it?

**Comment by drn05r** [comment]
There was a deliberate choice to not use the EPrints::Utils::REGEX_PASSWORD for the database password.  This is due to the database typically being hosted on the same server, so forcing those setting up the database to have to set a minimum length password would have been annoying without adding any significant extra security.

As this is public GitHub repository, there is nothing to stop you forking it into your own repository, making the changes you want and submitting a pull request to merge you changes back into the main eprints3.4 Git repository.
