### ISSUE TITLE
´send_alerts <repoID> weekly´ causes several 'Use of uninitialized value ...'

### ISSUE THREAD

**Issue by Pfiffikus** [eprints/eprints3.4#18]
When executing aforementioned command I receive
`Use of uninitialized value in string eq at /usr/share/eprints/bin/../perl_lib/EPrints/Search/Condition/Control.pm line 48.`
`Use of uninitialized value in string eq at /usr/share/eprints/bin/../perl_lib/EPrints/Search/Condition/Or.pm line 50.`
`Use of uninitialized value in string eq at /usr/share/eprints/bin/../perl_lib/EPrints/Search/Condition/Or.pm line 53.`
`Use of uninitialized value in string eq at /usr/share/eprints/bin/../perl_lib/EPrints/Search/Condition/And.pm line 54.`
`Use of uninitialized value in string eq at /usr/share/eprints/bin/../perl_lib/EPrints/Search/Condition/And.pm line 57.`
Fortunately the alerts are sent nevertheless :-)

**Comment by drn05r** [comment]
This looks as though it should be simple to fix.  I will add to 3.4.2 milestone.

**Comment by drn05r** [comment]
Could not reproduce.  Please could you provide the saved search 'spec' string that led to send_alerts to generating these error messages, e.g. 

?plugin=Internal&searchid=staff&dataset=eprint&exp=0%7C1%7C-date%2Fcreators_name%2Ftitle%7Ceprint%7C-%7Ceprint_status%3Aeprint_status%3AANY%3AEQ%3Ainbox+buffer+archive+deletion%7Ctype%3Atype%3AANY%3AEQ%3Aarticle%7C-%7Cmetadata_visibility%3Ametadata_visibility%3AANY%3AEQ%3Ashow"

**Comment by Pfiffikus** [comment]
The working search is `http://sub.domain.tld/cgi/search/archive/advanced?dataset=archive&screen=Search&_action_search=Search&title_merge=ALL&title=&creators_name_merge=ALL&creators_name=&corp_creators_merge=ALL&corp_creators=&abstract_merge=ALL&abstract=&date=&keywords_merge=ALL&keywords=&note_merge=ALL&note=&eprintid=&projects_merge=ALL&projects=&divisions_merge=ANY&id_number_merge=ALL&id_number=&editors_name_merge=ALL&editors_name=&publication_merge=ALL&publication=&festphase=&ton=&sorbat=&sorbens=&system=.*Fe%5C%28III%5C%29.*&temperature_Tmin=&temperature_Tmax=&subjects=Loeslichkeit&subjects_merge=ANY&satisfyall=ALL&order=-date%2Fcreators_name%2Ftitle`
but the original saved search was 'Saved search conditions:
Subjects matches any of "Löslichkeit" AND System is ".*Fe\\\\(III\\\\).*"' (… and seems to be broken, i.e. is nonsense).
Hopefully the [`send_alterts` verbose output](https://github.com/eprints/eprints3.4/files/4492480/sa.log) helps to track down the 'error'?

**Comment by drn05r** [comment]
I expected you may have hit the issue with the field that stores the spec for the saved search not being long enough.  Please check to see that "DESCRIBE saved_search;" from MySQL looks like:

+-----------+--------------+------+-----+---------+-------+
| Field     | Type         | Null | Key | Default | Extra |
+-----------+--------------+------+-----+---------+-------+
| id        | int(11)      | NO   | PRI | NULL    |       |
| userid    | int(11)      | YES  | MUL | NULL    |       |
| name      | varchar(255) | YES  |     | NULL    |       |
| spec      | longtext     | YES  |     | NULL    |       |
| frequency | varchar(255) | YES  | MUL | NULL    |       |
| mailempty | varchar(5)   | YES  | MUL | NULL    |       |
| public    | varchar(5)   | YES  | MUL | NULL    |       |
+-----------+--------------+------+-----+---------+-------+

In particular that the spec line is longtext.  If not modify the table to change the spec field to longtext.  If that is the case.  Please could you do a mysql select for the saved_search you are having problems with, use the following line (ending with '\G' rather than ';') to better format the output:

SELECT * FROM saved_search where ID = <ID>\G

Then I can check the spec is valid and there is not anything else odd about the saved search record.

**Comment by drn05r** [comment]
If you do need to modfify the spec field to make it longtext.  Make sure you delete the broken saved_search and then create as new identical saved_search for testing.

**Comment by Pfiffikus** [comment]
> In particular that the spec line is longtext.
it is :), cf. | spec | longtext | YES | | NULL | |

> SELECT * FROM saved_search where ID = \G
`spec: ?plugin=Internal&searchid=advanced&dataset=archive&exp=0%7C1%7C-date%2Fcreators_name%2Ftitle%7Carchive%7C-%7Csubjects%3Asubjects%3AANY%3AEQ%3ALoeslichkeit%7Csystem%3Asystem%3AALL%3AEQ%3A.*Fe%5C%5C%5C%5C(III%5C%5C%5C%5C).*%7C-%7Ceprint_status%3Aeprint_status%3AANY%3AEQ%3Aarchive%7Cmetadata_visibility%3Ametadata_visibility%3AANY%3AEQ%3Ashow`

**Comment by drn05r** [comment]
I have created a saved search with exactly the same spec and I do not see the error messages you are getting when I run send_alerts from the command line and through cron and I cannot reproduce the same error messages.  I cannot think of anything that would have fixed this since the 3.4.1 release that would have fixed this.  If you have a test instance you can update to the HEAD on GitHub and also run epadmin_update to make sure all required fields are present.  I initially noticed I did not have a system field so when I was in the individual saved search page it showed "[error in script]" rather than a human readable version of the search spec.  This was fixed by add the field and running epadmin update.

**Comment by Pfiffikus** [comment]
Okay, let's wait and see … what will happen for 3.4.2 :-)
As initially mentioned, I will fix the wired saved_search and keep an eye on further behaviour; fortunately the server is up & running ...
Many thanks for your debugging attempts nevertheless!
