### ISSUE TITLE
Curious RegExp - probably incorrect

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/eprints3.4#191]
NB This has existed in EPrints for a long time!

https://github.com/eprints/eprints3.4/blob/e34c7d85752629ff52a95d567a1f29a8cc75e48d/perl_lib/EPrints/Apache/Rewrite.pm#L768
I'm not quite sure what this is _trying_ to do.
It currently matches `view$stuff` (a literal dollar-sign), which seems a little strange.

It possibly should be:
`if( $uri =~ m! ^$urlpath/view(/|$) !x )`

The current RegExp means a request for e.g. `[server]/view$bobbins` creates:
`[ARCHIVE_ROOT]/html/en/html/view$bobbins.html` (and `.page` etc.).
A request for `[server]/view$bobbins/` creates a directory and associated index files within.
The generated files only behave as regular view pages - no additional data is presented in the, but it was surprising to find these files/directories on my server!

**Comment by drn05r** [comment]
So it looks to me that it is trying to match all three of the following, in case someone creates a link to the top level 'view' page without a trailing slash:

/view
/view/
/view/year

However, any requests for /view will automatically redirect to /view/ by other means, so as you have determined in #192 pull request the whole `(/|\$.*)` can be removed.  However, if you did need a match for all three of the above you would need something like: `^$urlpath/view(/?|/.*)$`.  My initial thought was that that would not work because the last $ would be confused with the start of a scalar variable (like $urlpath) but it seems as though the can be read by Perl with the correct intepretation.  However, this is all hypothetical, as your solution in #192 does the job and is much simpler.
