### ISSUE TITLE
Add sentinel to workflow forms to prevent data loss

### ISSUE THREAD

**Issue by dgc** [eprints/eprints3.4#264]
For workflow pages that are very long (e.g. take several seconds to appear) there is an opportunity for data loss if the browser has not received the complete workflow form. This is an issue for EPrints because action buttons ("Prev", "Save and Return", etc.) can be shown before the workflow form.

Add a sentinel form entry as the final part of the form so that when the user clicks on an action it checks that the sentinel is present before updating the data object.

If the sentinel is not present then show the page again (as if you had pressed an internal button) with a notice saying to wait and try again.

**Comment by dgc** [comment]
After discussion with @drn05r it was decided to move the CSRF token to the end of the workflow form to act as the sentinel.

**Comment by drn05r** [comment]
Unfortunately, there is no generic way to add the `csrf_token` at the end rather than the beginning of a form.  Therefore, trying to use this to solve the problem is no good.  This is a shame as still would have been a generic solution.

@dgc has said he will look at this as it is only really required in complex forms that may be slow to load.

**Comment by drn05r** [comment]
I don't think there is sufficient benefit for the complexity of implementing this.
