### ISSUE TITLE
Text::Unidecode outdated

### ISSUE THREAD

**Issue by Pfiffikus** [eprints/eprints3.4#27]
referring to [ChangeLog of Text::Unidecode](https://metacpan.org/source/SBURKE/Text-Unidecode-1.30/ChangeLog) also this module should be extracted from [EPrints release](https://github.com/eprints/eprints3.4/blob/fabcf978b3dcc7e07ce443ef82d68c2dd9eb7f1d/perl_lib/Text/Unidecode.pm#L3) and added to the required modules!? Or is there a special extension?

**Comment by drn05r** [comment]
I can see that there are DEB and RPM packages for this in Ubuntu 16.04 and 18.04 and RHEL/CentOS 6, 7 and 8, so it makes sense this should be added as a package dependency for EPrints rather than having it in core code so it can get out of date.  It is possible that it EPrints relies on something from the specific version under perl_lib, so this will need to be tested.
