### ISSUE TITLE
extension for multiple recipients of saved search results is incomplete

### ISSUE THREAD

**Issue by Pfiffikus** [eprints/eprints3.4#270]
If I scanned the 3.4.4 code correctly, the default setting for `saved_search_additional_recipients` is missing.
For more convenience some hints (or even a script) should be given how to extend existing databases.

Currently the upgraded instance complains:
`DBD::mysql::st execute failed: Unknown column 'additional_recipients' in 'field list' at /usr/share/eprints3/perl_lib/EPrints/Database.pm line 1003.`
`SQL ERROR (execute): SELECT 'id','userid','name','spec','frequency','mailempty','additional_recipients','public' FROM 'saved_search' WHERE 'id' IN (1,2,3)`
`SQL ERROR (execute): Unknown column 'additional_recipients' in 'field list'`

**Comment by drn05r** [comment]
I cannot replicate the error messages you reported.  Are you sure you ran `epadmin update <repoid>` to make sure any new fields since your previous version are added to the database.  

Doing the above should solve the error messages but `additional_recipients` field will still need to be added to a copy of `workflows/saved_search/default.xml` in the archive's `cfg` directory and `$c->{saved_search_additional_recipients}` will need to be set as true.  This is not documented, so could benefit from some documentation.  I will look into creating such documentation.

**Comment by drn05r** [comment]
I have added documentation at https://wiki.eprints.org/w/Additional_Recipients_on_Saved_Searches and linked this from the change log on https://wiki.eprints.org/w/EPrints_3.4.4

I don't think a change should be made to include additional_recipients in the saved search workflow by default.  This is something a repository owner should decide.  As they may not want to trust their users to add additional recipients to saved searches appropriately.

**Comment by Pfiffikus** [comment]
> Are you sure you ran `epadmin update <repoid>` ...
obviously I missed the final run after some dry runs ;(
Now the error message is gone :)
