### ISSUE TITLE
BibTex parses CiteKey as undefined when whitespace is present

### ISSUE THREAD

**Issue by fatchild** [eprints/eprints3.4#273]
For example the first BibTex formatted item below contains whitespace where you would expect the CiteKey (https://www.bibtex.com/g/bibtex-format/#citekey). This causes the parser to return `undef` and the BibTex import module cannot loop over the attributes . When the CiteKey is completely empty, as in the 2nd example, an error is thrown `Malformed entry (key contains illegal characters)`. When the CiteKey is omitted, there is no issue. 

```BibTex
@phdthesis { ,
	title = {fake title 1},
}

@phdthesis {,
	title = {fake title 2},
}

@phdthesis {
	title = {fake title 3},
}
```

`/opt/eprints3/flavours/pub_lib/plugins/EPrints/Plugin/Import/BibTeX.pm`
```perl
while(my $entry = $parser->next)
```

### Possible fix: 
Throw error when the BibText entry is empty / undef malformed.
```perl
                    if (not defined $1) {
                    $current_entry->error("Malformed Key: CiteKey is empty i.e. '\@phdthesis { ,' To fix, remove blank space and comma before first attribute.  '\@phdthesis {'");
                        return $current_entry;
                    }
```

**Comment by fatchild** [comment]
Another possible fix could be to pass over the value and just import the attributes which are not undef.

`flavours/pub_lib/plugins/BibTeX/Parser.pm`
```perl
                        return "EMPTY_ATTRIBUTE" if not defined $1;
```

`flavours/pub_lib/plugins/EPrints/Plugin/Import/BibTeX.pm`
```perl
        while(my $entry = $parser->next)
        {
                next if $entry eq "EMPTY_ATTRIBUTE";
```

**Comment by drn05r** [comment]
This is a difficult choice to make between ease of use (e.g. importing all valid items even if some invalid items are present) over making the user aware the import has not been comprehensive.  This is part of the reason for the "Test without Importing" button.

I think the best compromise is to raise warnings but still import.  If the message at the end which shows how many items were imported could also display how many items could not be imported because they were malformed in some way, that would be useful.  Obviously, these changes are in addition to fixing the problem with empty cite keys.
