### ISSUE TITLE
some uninitialized values in perl_lib/EPrints/Search/Condition/*

### ISSUE THREAD

**Issue by Pfiffikus** [eprints/eprints3.4#283]
When running `send_alerts [repoID] --verbose -verbose weekly`
I receive the attached [output](https://github.com/eprints/eprints3.4/files/10444999/send_alerts.log); no idea, if the sending was successful.

**Comment by drn05r** [comment]
I think setting `--verbose -verbose` is rather good at obfuscating any messages you might, see on in this case not see.  If I run the same command I do see a line inside the other verbose output just before the final `Database execute debug` line:

`Sending out alert #3 to eprints@example.eprints.org`

This would be clearer if you only used a single `--verbose` however, it looks from your output that some issue occurs that prevent the email being sent and rather than printing an error message it prints nothing.  Also, the uninitialized value warnings are a bit of a concern.  This suggests to me that the SQL query that runs finds no results possibly due to the issues with the uninitialized value warnings.  If the saved search does not state that email should be sent even if there are no results, then you will not get a log line line the one above.

I think from a code development point of view, it is not unreasonable to have some output when `--verbose` is set to say that no email was sent as there were not results and the saved search's mailempty attribute was set to false.

The reason why you are getting uninitialized value warnings is not clear from the send_alerts log.  If you can give me a URL I can access that show this search query on your repository I might be able to investigate further.

**Comment by Pfiffikus** [comment]
Unfortunately our repository is disconnected from the internet, but I could provide some more information on request!

**Comment by drn05r** [comment]
Feel free to provide some more information.  I am not sure how you can provide this privately without me having to give you my contact information publicly.

**Comment by drn05r** [comment]
Actually if you can just provide here what is printed under the Saved search conditions when you look at the saved search view page at: 

`/cgi/users/home?screen=Workflow%3A%3AView&dataset=saved_search&dataobj=...` 

That may be useful.  Better still the value for the spec field in the saved_search database table:

`SELECT spec FROM ssaved_search WHERE id = <saved_search_id>;`

This should look something like: 

`?plugin=Internal&searchid=advanced&dataset=archive&exp=0%7C1%7C-date%2Fcreators_name%2Ftitle%7Carchive%7C-%7Cdate%3Adate%3AALL%3AEQ%3A2011-01-01-%7C-%7Ceprint_status%3Aeprint_status%3AANY%3AEQ%3Aarchive%7Cmetadata_visibility%3Ametadata_visibility%3AANY%3AEQ%3Ashow`

**Comment by Pfiffikus** [comment]
saved search view page: Schlagworte Oder-Verknüpfung "Löslichkeit" UND System ist ".*Fe\\\\(III\\\\).*" . Ergebnisse sortiert nach -Datum, Autoren, Titel

`SELECT spec FROM saved_search WHERE id = 5;`
`?plugin=Internal&searchid=advanced&dataset=archive&exp=0%7C1%7C-date%2Fcreators_name%2Ftitle%7Carchive%7C-%7Csubjects%3Asubjects%3AANY%3AEQ%3ALoeslichkeit%7Csystem%3Asystem%3AALL%3AEQ%3A.*Fe%5C%5C%5C%5C(III%5C%5C%5C%5C).*%7C-%7Ceprint_status%3Aeprint_status%3AANY%3AEQ%3Aarchive%7Cmetadata_visibility%3Ametadata_visibility%3AANY%3AEQ%3Ashow`

**Comment by drn05r** [comment]
I have tried to replicate an equivalent saved search on my test repository and have not been able to replicate this issue.  However, I think this may be due to me not matching the same type of field for `system`.  Please could you confirm what the metafield type is for the `system` field.

**Comment by drn05r** [comment]
Please could you also provide the contents of your archive level config files: `eprint_search_advanced.pl` and `eprint_search_staff.pl` as well as the field configuration (maybe in `eprint_fields.pl`) for the `system` field.  I have worked out it is a multiple field but cannot work out how it is configured to generate an SQL query that uses the `REGEXP` operator.

**Comment by Pfiffikus** [comment]
[cfg.zip](https://github.com/eprints/eprints3.4/files/10901115/cfg.zip)

`
        name => 'system',
        input_cols => '80',
        input_boxes => '3',
        type => 'pattern',
        multiple => 1,
        browse_link => 'system',
        input_ordered => 0
`

> ... but cannot work out how it is configured ...

sorry, `system` is home-brewed, but hopefully not causing this issue?

**Comment by drn05r** [comment]
There were two separate issues here:
1. `EPrints::Search::Condition::Regexp` did not define an `op` attribute like other search conditions do.  I have now added this.  I don't think this really broke anything, it just generate the `Use of uninitialized value in string eq at...` error messages you reported in your original output log.
2. The specification for a search gets escaped before it is saved.  However, if it is already escaped, it gets escaped again.  By the time it is called as an SQL query as part of `send_alerts` it is escaped with 8 `\`s, where it should only be escaped with 2 `\`s.  I have modified the code that prepare the search specification for being saved to avoid double-escapes like this.
