### ISSUE TITLE
Missing subroutine after install from Debian Package.

### ISSUE THREAD

**Issue by fredrik-ndjurumana** [eprints/eprints3.4#337]
I installed Eprints 3.4.4 from Debian Packages. It was going well until I got error when adding, edit, or View deposit item.
This is is the error log i got
`Undefined subroutine &EPrints::Extras::render_paras called at /usr/share/eprints/perl_lib/EPrints/MetaField.pm line 1040`
The error gone after i added the subroutine manually to the Extras.pm file, reload repository configuration and then restart the webserver.
I have no idea, what errors will come next time because of the missing subroutine.

**Comment by drn05r** [comment]
This is odd. EPrints::Extras::render_paras did not exist until EPrints 3.4.5 and I am unaware of it being used in any code or configuration prior to 3.4.5 and it if did things would break for all repositories.  Have you modified any configuration in a cfg.d file in any of the following directories:

- /usr/share/eprints/lib/cfg.d/
- /usr/share/eprints/flavours/pub_lib/cfg.d/
- Any /usr/share/eprints/archives/*/cfg/cfg.d/ directory

If so check over these directories to see if you can find the text `render_paras`.  If you find this make sure it is:
`render_single_value => 'render_paras',`
rather than:
`render_single_value => "EPrints::Extras::render_paras",`
and also make sure that there is a file called: **/usr/share/eprints/flavours/pub_lib/cfg.d/render_paras.pl** present.

**Comment by fredrik-ndjurumana** [comment]
I didn't change anything in cfg.d directory. what i did is, i added the extra_paras subroutine directly into MetaField.pm file, that i copied from the source on github.

**Comment by drn05r** [comment]
So was you change to MetaField.pm before or after to first observed the error message about the missing subroutine? (Was the change to try tof fix this error or some other bug)  Please can you provide a diff of what you change in MetaField or at least the MetaField.pm you are currently using.

Looking at [line 1040 of MetaField.pm for EPrints 3.4.4](https://github.com/eprints/eprints3.4/blob/f31a87f8afd4b3c593f12e8a64d30bb081533a88/perl_lib/EPrints/MetaField.pm#L1040), (this becomes line 1047 in EPrints 3.4.5), I can see that it tries calls a predefined subroutine (like `EPrints::Extras::render_paras`) rather than call a subroutine defined as a variable with in configuration (e.g. `$c->{my_subroutine}`).  You must have some configuration some where in your archive that uses `EPrints::Extras::render_paras` or otherwise modified core configuration to reference it, as it has only existed since EPrints 3.4.5 and therefore would not have been referenced anywhere in the 3.4.4 codebase including core configuration.

**Comment by drn05r** [comment]
This does not require a core code fix AFAICT.

**Comment by drn05r** [comment]
Unfortunately, we no longer do deb or rpm builds for EPrints as we have found that as EPrints has quite complex dependencies including those that cannot be satisfied by the package managers.  For some time we have recommended that these packages (deb and rpm) only be used for demo purposes.  Also, installing from a package means in may get upgraded unexpectedly.  EPrints due to the extent of its customisability is something you need a managed process for upgrading.  As it would be all but impossible to write a reliable in-package upgrade script due to all this customisability.

If I get a chance, I will see if I can test and if it is also broken for me rebuild this old deb package.
