### ISSUE TITLE
OAI2 ListRecords returning blank page

### ISSUE THREAD

**Issue by opmat** [eprints/eprints3.4#408]
I updated EPrints from version 3.4.4 to version 3.4.6 because deposited papers were no longer been index on Google Scholar.
However, with EPrints 3.4.6 , OAI2 Listrecords returns an empty page but the same page loads. if I restore it back to version 3.4.6

This is my Listrecords URL: https://tudr.org/cgi/oai2?verb=ListRecords&metadataPrefix=oai_dc

What can be the issue? Someone please help.

And I am still not sure why documents deposited since June 2024 stopped being indexed on Google Scholar but appears on Google Search.

Thank you

**Comment by drn05r** [comment]
I have tested this on a number of EPrints repository that have or are in the process of being upgraded to EPrints 3.4.6 and have not been able to reproduce this issue.

I have just gone to https://tudr.org/cgi/oai2?verb=ListRecords&metadataPrefix=oai_dc and this does not look empty and I can also see that you are currently running EPrints 3.4.6.  Is this still an issue or have you fixed the problem.  If not could you provide any URLs you are still having issues with and description of what is wrong (if it it snot obvious, like an empty page).

Regarding Google Scholar indexing, this a bit unknown quantity.  AFAIAA, they use the year view on your EPrints repository to discover new items.  This should be regularly updated either by a cron job or the cache expiring (after 24 hours).  I can see that https://tudr.org/view/year/2024.html was last generated earlier today, so that is working as expected.  I can also see that you use long URLs (e.g. https://tudr.org/id/eprint/2818/ rather than https://tudr.org/2818/) which if you used the short URLs may have been a reason for missing Google Scholar indexing. 

I can see that your robots.txt has default configuration, so this should not be causing an issue and also your sitemap.xml listing published items look pretty much up to date (items deposited after the start of October 2024).  Therefore, there is not much more you can do.  However, it would be useful to know if anything changed with your EPrints repository in June 2024? Did you change the hostname or any configuration relating to the URLs for publications (e.g. enable HTTPS or HTTP->HTTPS redirects).  Did you enable long URLs for the first time?  

It should make no difference (but I don't know what metrics Google Scholar use to measure suspiciously behaviour of OA repositories), but did the IP address or the version of Apache webserver you run your EPrints repository on change?  It is the sort of thing I could see being used to temporarily suspend indexing, until they could verify the change was not suspicious.

**Comment by opmat** [comment]
Thanks for the follow-up. I have been able to resolve the issue after about 3 trials. However, the Google Scholar indexing issue persists and I cannot remember making any changes around that period, although I will still confirm these. Hopefully, this changes soon.Thank you once again for the great work you are doing.
 

    On Monday, 11 November 2024 at 17:28:25 GMT+1, David R Newman ***@***.***> wrote:  
 
 


I have tested this on a number of EPrints repository that have or are in the process of being upgraded to EPrints 3.4.6 and have not been able to reproduce this issue.

I have just gone to https://tudr.org/cgi/oai2?verb=ListRecords&metadataPrefix=oai_dc and this does not look empty and I can also see that you are currently running EPrints 3.4.6. Is this still an issue or have you fixed the problem. If not could you provide any URLs you are still having issues with and description of what is wrong (if it it snot obvious, like an empty page).

Regarding Google Scholar indexing, this a bit unknown quantity. AFAIAA, they use the year view on your EPrints repository to discover new items. This should be regularly updated either by a cron job or the cache expiring (after 24 hours). I can see that https://tudr.org/view/year/2024.html was last generated earlier today, so that is working as expected. I can also see that you use long URLs (e.g. https://tudr.org/id/eprint/2818/ rather than https://tudr.org/2818/) which if you used the short URLs may have been a reason for missing Google Scholar indexing.

I can see that your robots.txt has default configuration, so this should not be causing an issue and also your sitemap.xml listing published items look pretty much up to date (items deposited after the start of October 2024). Therefore, there is not much more you can do. However, it would be useful to know if anything changed with your EPrints repository in June 2024? Did you change the hostname or any configuration relating to the URLs for publications (e.g. enable HTTPS or HTTP->HTTPS redirects). Did you enable long URLs for the first time?

It should make no difference (but I don't know what metrics Google Scholar use to measure suspiciously behaviour of OA repositories), but did the IP address or the version of Apache webserver you run your EPrints repository on change? It is the sort of thing I could see being used to temporarily suspend indexing, until they could verify the change was not suspicious.

**Comment by drn05r** [comment]
Closing this issue, as it looks to be pretty much resolved.
