### ISSUE TITLE
Boolean field has inconsistent phrase names

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/eprints3.4#415]
Traditionally boolean values have used uppercase TRUE / FALSE suffixes in their respective labels.

The Boolean metafield now has a mix of uppercase and lowercase phrase references, depending on the input style:

Uppercase: https://github.com/eprints/eprints3.4/blob/12426a98132d05b7cf1257824bcd3b212fb06a07/perl_lib/EPrints/MetaField/Boolean.pm#L90-L91

Lowercase: 
https://github.com/eprints/eprints3.4/blob/12426a98132d05b7cf1257824bcd3b212fb06a07/perl_lib/EPrints/MetaField/Boolean.pm#L135
https://github.com/eprints/eprints3.4/blob/12426a98132d05b7cf1257824bcd3b212fb06a07/perl_lib/EPrints/MetaField/Boolean.pm#L147

The code here has changed a bit. In v3.3 there was a wrapping phrase that use pins to include the true/false values, and these pins were in lowercase:
https://github.com/eprints/eprints/blob/ccf42ae1b6dcfd5ecf9d6e4d963042e9eba55775/lib/lang/en/phrases/system.xml#L1482-L1485

I'm not sure whether these phraseids should be aligned back to the traditional uppercase versions, or just documented on the wiki as the different phrases needed for a 'radio' input style as compared to a 'menu' input.

**Comment by drn05r** [comment]
Unfortunately, this looks like it has been present since the initial release of 3.4.  Therefore, it is established and cannot be removed.  The best solution I can think of is that if the radio phrase is set but the fieldopt one is not then it uses the radio phrase.  This means if you change to input_style = menu you don't need to add new phrases.  However, if you have configured fieldopt phrases these don't suddenly change to the radio phrases and you cannot figure out how to change them back as you now would need to change the radio phrases rather than the fieldopt ones.
