### ISSUE TITLE
some item editing could _not_ be cancelled

### ISSUE THREAD

**Issue by Pfiffikus** [eprints/eprints3.4#46]
Reordering of the creators or changing to the files stage, e.g., causes an immediate saving of the current state, thus could _not_ be undone by cancelling the modification.

If this behaviour is due to the implementation and hardly to prevent, then the user should be informed after hitting the cancel button!

**Comment by drn05r** [comment]
This is the intended behaviour and as far as I know has always been the case.  I don't think there is any easy way to inform users when they hit the cancel button.  I think the best option would be to add warnings either to the help text of otherwise within the workflow above multiple fields that might get re-ordered.
