### ISSUE TITLE
Views with similar label are generated several times

### ISSUE THREAD

**Issue by mpbraendle** [eprints/eprints3.4#55]
The grep statement in 

https://github.com/eprints/eprints3.4/blob/999af95180719e9fdf35aca225b3ea5ede8270c1/bin/generate_views#L217

matches to fuzzily. As a consequence, views with similar labels are generated several times, hurting performance of the view generation.

Example: Two configured views, one named "a", the other "ab".
Because "a" matches "ab", it will be generated also when generate_views {repo} --view ab is called.

**Comment by mpbraendle** [comment]
Please fix also for EPrints 3.3.x

**Comment by drn05r** [comment]
I have just tested with the following three calls without making any changes yet:

/opt/eprints3/bin/generate_views ARCHIVE_NAME --view=year 
/opt/eprints3/bin/generate_views ARCHIVE_NAME --view=yea 
/opt/eprints3/bin/generate_views ARCHIVE_NAME --view=years

 The first works as expected and the next two say the view is unknown.  Please could you provide and example of where fuzzy matches leads to views being generated multiple times.

**Comment by mpbraendle** [comment]
Of course, as I wrote in my first post, the views with similar names must be configured, and then the bug hits. You did not configure a yea and years view.

In our case, it was
subjects
subjectsnew
scopussubjects

So, if scopussubjects is called, subjects is executed, too.

**Comment by drn05r** [comment]
Ah, I did not interpret the logic correctly.  It was not if you speciifed a vague view ID in the command it would generate all views that match but that if you have two views that share a substring then calling the command with the view ID set as the the longer stringed one will also call the shorter stringed one.  As it tries to match the view IDs specified in the configuration against the some part of view ID specified in the command rather than the other way around.
