### ISSUE TITLE
upper case letters in user's name could cause trouble

### ISSUE THREAD

**Issue by Pfiffikus** [eprints/eprints3.4#57]
At login the case does _not_ matter, as long there is no user with the 'same' (apart from case) username (… because the password mapping fails in this case?!). The admin's searches use a case-sensitive username.

I would prefer lower case usernames, but could also imagine a correction of login's behaviour.

**Comment by drn05r** [comment]
It should be impossible to add a second user whose username only varies due to case, so it is not worth making any changes to user login.  Many login systems don't care about case and because the original username may have been set from data from the user's institution rather than the user themselves, the account may have been created with uppercase letters in the username but the user always logins in with an all lower case username.

Regarding searching for users.  a Username is typed as a Id MetaField.  Id fields only match exactly including on case.  I think the best solution would be to add a new MetaField type that is exactly the same as the Id MetaField (i.e. a match must be exact rather than fuzzy, on individual words or a partial string) but be case insensitive.  This would be useful for the email field as well. As although the RFC says email address are case sensitive, I don't know anyone who runs a mail server with case sensitive email addresses.
