### ISSUE TITLE
workflow list of unspecified fields isn't sorted

### ISSUE THREAD

**Issue by Pfiffikus** [eprints/eprints3.4#70]
The list of core workflow is neither sorted by variable name (unwanted) nor by phrase name (recommended) thus the link for editing to still empty fields is hard to find. The ordering seems to depend on database scheme, i.e. table definition ...

**Comment by drn05r** [comment]
Yes, this is ordered by the order in the database table itself.  I am not sure how easy this is to fix.  If it is trivial it may sneek into 3.4.2 otherwise this may have to wait until 3.4.3.

**Comment by drn05r** [comment]
This is not a trivial change even to fix based on field name and even more effort to fix based on field label (i.e. that said in phrases).  I think this will need to wait to 3.4.3.

**Comment by Pfiffikus** [comment]
please don't worry; it's an appreciated enhancement ...

**Comment by drn05r** [comment]
@Pfiffikus After discussion with other developers we decided against fixing this for the following reasons (in most significant reason order):

1. There is limited user experience improvement (nobody else has requested for this to be fixed).
2. The amount of effort required to fix this issue is significant as you need to resolve the phrase for the field to get the correct order as ordering by field name might been the fields still do not display in alphabetical order.  This is further complicated by multiple languages for phrases that means ordering may be different depending on the language current set by /cgi//set_lang.
3. There is a small chance that fixing this will required changing shared functionality that might break something elsewhere and it is not worth risking this for such a minimal improvement.
