### ISSUE TITLE
Rate limit password reset emails

### ISSUE THREAD

**Issue by drn05r** [eprints/eprints3.4#96]
Password resets could spam users with large amounts of unsolicited emails.  There should be a limit on how many passwords reset emails can be sent out in a particular time frame.  This will need two new MetaFields in the user record and two configuration settings.  One for the timeframe (a day seems a sensible default) and one for number of resets (3 seems a sensible default).  If a password is successfully reset these user record values will be reset.

**Comment by drn05r** [comment]
This was already limited to one request every 24 hours.  It has been improved so hours between permitted reset requests can be made shorter or longer.

**Comment by steswinbank** [comment]
I appreciate this is closed, but have struggled to find anywhere else to report this. I woke up to >1,000 reset emails this morning for this very reason.

**Comment by drn05r** [comment]
steswinbank: I am not sure which version of EPrints 3.4 you are running but you should not be spammed by password reset emails for the same account as only one should be able to be sent in a 24-hour period.  All this issue fixed was the timeframe between  when the next password reset email can be sent.

Maybe the issue you have is from lots of accounts being created and then generating password resets.  You need to give me a bit more detail about what version of EPrints you are running and contents of the emails you received so I can understand whether this is multiple EPrints user accounts with the same/similar email address or one account that has somehow managed to generate multiple password reset emails in a short space of time which should not be possible in any version of EPrints 3.4.

**Comment by drn05r** [comment]
https://wiki.eprints.org/w/Main_Page has advice on various ways to report or discuss issues with EPrints.

**Comment by steswinbank** [comment]
Hi David Sorry for the false alarm – I’ve subsequently removed my comment. I didn’t mean to post it in the eprints repo – was a general problem with Github. Apologies for the distraction. Steve  From: David R NewmanSent: 28 March 2021 13:52To: eprints/eprints3.4Cc: steswinbank; CommentSubject: Re: [eprints/eprints3.4] Rate limit password reset emails (#96) steswinbank: I am not sure which version of EPrints 3.4 you are running but you should not be spammed by password reset emails for the same account as only one should be able to be sent in a 24-hour period. All this issue fixed was the timeframe between when the next password reset email can be sent.Maybe the issue you have is from lots of accounts being created and then generating password resets. You need to give me a bit more detail about what version of EPrints you are running and contents of the emails you received so I can understand whether this is multiple EPrints user accounts with the same/similar email address or one account that has somehow managed to generate multiple password reset emails in a short space of time which should not be possible in any version of EPrints 3.4.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
